/**
 * Which edition of OWASP ASVS the product maps against, and which is current.
 *
 * The mapping in ./asvs.ts (generated by scripts/build-asvs.mjs) is pinned to
 * ASVS 4.0.3, by decision: remapping to 5.0.0 is a re-derivation of every
 * finding-to-requirement pairing, not a version bump. ASVS 5.0.0 is the current
 * release, and it reorganises the chapters, so a 4.0.3 requirement id names a
 * different requirement -- or none -- in 5.0.0.
 *
 * Every screen that renders the mapping says both things, and says what the
 * mapping is: which requirements this engine's tests bear on and what they
 * found. It is not a conformance claim; a requirement no scan reaches is
 * untested, not met. Kept here, beside the generated file rather than in it,
 * so a regeneration cannot drop it.
 */
export { ASVS_VERSION as ASVS_MAPPED_VERSION } from "./asvs";

/** The current OWASP ASVS release. Hand-maintained: update when OWASP publishes. */
export const ASVS_CURRENT_RELEASE = "5.0.0";
